[package]
name = "sol-chad-mcp"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk", branch = "main", features = [
    "server",
    "transport-sse-server",
    "transport-io",
] }
sysinfo = "0.34.2"
schemars = { version = "0.8", optional = true }
futures = "0.3"
rand = { version = "0.9" }
reqwest = { version = "0.12", features = ["json"] }
ta = "0.5"

[[example]]
name = "sol_chad_mcp"
path = "src/main.rs"
